version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    volumes:
      - var/run/docker.sock:/var/run/docker.sock:ro
      - ${RSA_KEYS_FILEPATH}:/certs:ro
      - portainer_data:/data:rw
    command: --ssl --sslcert=/certs/${RSA_PUBLIC_KEY_FILENAME} --sslkey=/certs/${RSA_PRIVATE_KEY_FILENAME}
    ports:
      - "9443:9443"

volumes:
  "var/run/docker.sock": { }
  "portainer_data": { }