version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    network_mode: "host"
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: volume
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        volume:
          nocopy: true
      - type: volume
        source: ./portainer_data
        target: /data
        read_only: false
        volume:
          nocopy: true
      - type: volume
        source: ${RSA_KEYS_FILEPATH}
        target: /certs
        read_only: true
        volume:
          nocopy: true
    command: --ssl --sslcert=/certs/${RSA_PUBLIC_KEY_FILENAME} --sslkey=/certs/${RSA_PRIVATE_KEY_FILENAME}
    ports:
      - "9443:9443"